"""+===================================================================
 File:      Colors.py

 NightDriverController - (c) 2021 xcalibur839. All Rights Reserved.

    NightDriverController is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
 
    NightDriverController is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with NightDriverController.  It is normally found in copying.txt
    If not, see <https://www.gnu.org/licenses/>.

 Description:

    This list of colors was taken from pixeltypes.h HTMLColorCode of FastLED
    and adapted for Python. All members are static, so you can use Color.Blue
    to get the appropriate hex color data for example.
===================================================================+"""

# Predefined RGB colors
class Color:
    AliceBlue=bytes.fromhex("F0F8FF")
    Amethyst=bytes.fromhex("9966CC")
    AntiqueWhite=bytes.fromhex("FAEBD7")
    Aqua=bytes.fromhex("00FFFF")
    Aquamarine=bytes.fromhex("7FFFD4")
    Azure=bytes.fromhex("F0FFFF")
    Beige=bytes.fromhex("F5F5DC")
    Bisque=bytes.fromhex("FFE4C4")
    Black=bytes.fromhex("000000")
    BlanchedAlmond=bytes.fromhex("FFEBCD")
    Blue=bytes.fromhex("0000FF")
    BlueViolet=bytes.fromhex("8A2BE2")
    Brown=bytes.fromhex("A52A2A")
    BurlyWood=bytes.fromhex("DEB887")
    CadetBlue=bytes.fromhex("5F9EA0")
    Chartreuse=bytes.fromhex("7FFF00")
    Chocolate=bytes.fromhex("D2691E")
    Coral=bytes.fromhex("FF7F50")
    CornflowerBlue=bytes.fromhex("6495ED")
    Cornsilk=bytes.fromhex("FFF8DC")
    Crimson=bytes.fromhex("DC143C")
    Cyan=bytes.fromhex("00FFFF")
    DarkBlue=bytes.fromhex("00008B")
    DarkCyan=bytes.fromhex("008B8B")
    DarkGoldenrod=bytes.fromhex("B8860B")
    DarkGray=bytes.fromhex("A9A9A9")
    DarkGrey=bytes.fromhex("A9A9A9")
    DarkGreen=bytes.fromhex("006400")
    DarkKhaki=bytes.fromhex("BDB76B")
    DarkMagenta=bytes.fromhex("8B008B")
    DarkOliveGreen=bytes.fromhex("556B2F")
    DarkOrange=bytes.fromhex("FF8C00")
    DarkOrchid=bytes.fromhex("9932CC")
    DarkRed=bytes.fromhex("8B0000")
    DarkSalmon=bytes.fromhex("E9967A")
    DarkSeaGreen=bytes.fromhex("8FBC8F")
    DarkSlateBlue=bytes.fromhex("483D8B")
    DarkSlateGray=bytes.fromhex("2F4F4F")
    DarkSlateGrey=bytes.fromhex("2F4F4F")
    DarkTurquoise=bytes.fromhex("00CED1")
    DarkViolet=bytes.fromhex("9400D3")
    DeepPink=bytes.fromhex("FF1493")
    DeepSkyBlue=bytes.fromhex("00BFFF")
    DimGray=bytes.fromhex("696969")
    DimGrey=bytes.fromhex("696969")
    DodgerBlue=bytes.fromhex("1E90FF")
    FireBrick=bytes.fromhex("B22222")
    FloralWhite=bytes.fromhex("FFFAF0")
    ForestGreen=bytes.fromhex("228B22")
    Fuchsia=bytes.fromhex("FF00FF")
    Gainsboro=bytes.fromhex("DCDCDC")
    GhostWhite=bytes.fromhex("F8F8FF")
    Gold=bytes.fromhex("FFD700")
    Goldenrod=bytes.fromhex("DAA520")
    Gray=bytes.fromhex("808080")
    Grey=bytes.fromhex("808080")
    Green=bytes.fromhex("008000")
    GreenYellow=bytes.fromhex("ADFF2F")
    Honeydew=bytes.fromhex("F0FFF0")
    HotPink=bytes.fromhex("FF69B4")
    IndianRed=bytes.fromhex("CD5C5C")
    Indigo=bytes.fromhex("4B0082")
    Ivory=bytes.fromhex("FFFFF0")
    Khaki=bytes.fromhex("F0E68C")
    Lavender=bytes.fromhex("E6E6FA")
    LavenderBlush=bytes.fromhex("FFF0F5")
    LawnGreen=bytes.fromhex("7CFC00")
    LemonChiffon=bytes.fromhex("FFFACD")
    LightBlue=bytes.fromhex("ADD8E6")
    LightCoral=bytes.fromhex("F08080")
    LightCyan=bytes.fromhex("E0FFFF")
    LightGoldenrodYellow=bytes.fromhex("FAFAD2")
    LightGreen=bytes.fromhex("90EE90")
    LightGrey=bytes.fromhex("D3D3D3")
    LightPink=bytes.fromhex("FFB6C1")
    LightSalmon=bytes.fromhex("FFA07A")
    LightSeaGreen=bytes.fromhex("20B2AA")
    LightSkyBlue=bytes.fromhex("87CEFA")
    LightSlateGray=bytes.fromhex("778899")
    LightSlateGrey=bytes.fromhex("778899")
    LightSteelBlue=bytes.fromhex("B0C4DE")
    LightYellow=bytes.fromhex("FFFFE0")
    Lime=bytes.fromhex("00FF00")
    LimeGreen=bytes.fromhex("32CD32")
    Linen=bytes.fromhex("FAF0E6")
    Magenta=bytes.fromhex("FF00FF")
    Maroon=bytes.fromhex("800000")
    MediumAquamarine=bytes.fromhex("66CDAA")
    MediumBlue=bytes.fromhex("0000CD")
    MediumOrchid=bytes.fromhex("BA55D3")
    MediumPurple=bytes.fromhex("9370DB")
    MediumSeaGreen=bytes.fromhex("3CB371")
    MediumSlateBlue=bytes.fromhex("7B68EE")
    MediumSpringGreen=bytes.fromhex("00FA9A")
    MediumTurquoise=bytes.fromhex("48D1CC")
    MediumVioletRed=bytes.fromhex("C71585")
    MidnightBlue=bytes.fromhex("191970")
    MintCream=bytes.fromhex("F5FFFA")
    MistyRose=bytes.fromhex("FFE4E1")
    Moccasin=bytes.fromhex("FFE4B5")
    NavajoWhite=bytes.fromhex("FFDEAD")
    Navy=bytes.fromhex("000080")
    OldLace=bytes.fromhex("FDF5E6")
    Olive=bytes.fromhex("808000")
    OliveDrab=bytes.fromhex("6B8E23")
    Orange=bytes.fromhex("FFA500")
    OrangeRed=bytes.fromhex("FF4500")
    Orchid=bytes.fromhex("DA70D6")
    PaleGoldenrod=bytes.fromhex("EEE8AA")
    PaleGreen=bytes.fromhex("98FB98")
    PaleTurquoise=bytes.fromhex("AFEEEE")
    PaleVioletRed=bytes.fromhex("DB7093")
    PapayaWhip=bytes.fromhex("FFEFD5")
    PeachPuff=bytes.fromhex("FFDAB9")
    Peru=bytes.fromhex("CD853F")
    Pink=bytes.fromhex("FFC0CB")
    Plaid=bytes.fromhex("CC5533")
    Plum=bytes.fromhex("DDA0DD")
    PowderBlue=bytes.fromhex("B0E0E6")
    Purple=bytes.fromhex("800080")
    Red=bytes.fromhex("FF0000")
    RosyBrown=bytes.fromhex("BC8F8F")
    RoyalBlue=bytes.fromhex("4169E1")
    SaddleBrown=bytes.fromhex("8B4513")
    Salmon=bytes.fromhex("FA8072")
    SandyBrown=bytes.fromhex("F4A460")
    SeaGreen=bytes.fromhex("2E8B57")
    Seashell=bytes.fromhex("FFF5EE")
    Sienna=bytes.fromhex("A0522D")
    Silver=bytes.fromhex("C0C0C0")
    SkyBlue=bytes.fromhex("87CEEB")
    SlateBlue=bytes.fromhex("6A5ACD")
    SlateGray=bytes.fromhex("708090")
    SlateGrey=bytes.fromhex("708090")
    Snow=bytes.fromhex("FFFAFA")
    SpringGreen=bytes.fromhex("00FF7F")
    SteelBlue=bytes.fromhex("4682B4")
    Tan=bytes.fromhex("D2B48C")
    Teal=bytes.fromhex("008080")
    Thistle=bytes.fromhex("D8BFD8")
    Tomato=bytes.fromhex("FF6347")
    Turquoise=bytes.fromhex("40E0D0")
    Violet=bytes.fromhex("EE82EE")
    Wheat=bytes.fromhex("F5DEB3")
    White=bytes.fromhex("FFFFFF")
    WhiteSmoke=bytes.fromhex("F5F5F5")
    Yellow=bytes.fromhex("FFFF00")
    YellowGreen=bytes.fromhex("9ACD32")

    # LED RGB color that roughly approximates
    # the color of incandescent fairy lights,
    # assuming that you're using FastLED
    # color correction on your LEDs (recommended).
    FairyLight=bytes.fromhex("FFE42D")

    # If you are using no color correction, use this
    FairyLightNCC=bytes.fromhex("FF9D2A")